name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Bro !!!!"
      - name: Print goodbye
        run: echo "GoodBye !!!!"
      - name: Print Multiple Shell commands at once
        run: |
            echo "First Command"
            echo "Second Command"
      
  
